import Head from "next/head";
import FeaturedProduct from "../components/home/FeaturedProduct";
import Hero from "../components/home/Hero";
import UpcomingAuction from "../components/home/UpcomingAuction";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <section className="w-full bg-white pb-20">
      <Head>
        <title>Artsy.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Hero />
        <FeaturedProduct />
        <UpcomingAuction />
      </main>
    </section>
  );
}
