import Head from "next/head";
import Navbar from "../components/Navbar";
import bodyFont from "../public/fonts";

export default function Home() {
  return (
    <section className="w-full bg-white">
      <Head>
        <title>Artsy.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {/* 
      <div className={`font-sans ${bodyFont} font-bold text-[8rem]`}>
        Tommorow will come again
      </div> */}
    </section>
  );
}
